name: movie_app
description: "a new test project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # navigation
  auto_route: ^8.0.2

  #di
  get_it: ^7.6.7

  #networking
  retrofit: ^4.1.0
  dio: ^5.4.2+1

  #state management
  flutter_bloc: ^8.1.5

  #data-classes/unions/parser
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_config: ^2.0.2
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen/
  line_length: 100
  integrations:
    flutter_svg: true
  assets:
    exclude:
      - assets/fonts/*

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf